Add additional tech days
sourcebots/website pull request #22
Opened 2018-03-12 19:30 UTC by RealOrangeOne

2018-03-12 22:02 UTC, PeterJCLaw submitted a review, later dismissed
Both events have the same name, which is presumably an error.
Do the file names intentionally contain a space? (Previous tech days don't -- they use dashes instead)

2018-03-12 22:02 UTC, PeterJCLaw commented on content/events/2018/tech day-04-14.md
> +title: March Tech Day
since this is in April, perhaps it should be named as such?

2018-03-13 09:39 UTC, RealOrangeOne commented
D'oh, yes those are both errors :-1:

2018-03-13 18:56 UTC, kierdavis submitted a review, later dismissed

2018-03-15 17:42 UTC, RealOrangeOne commented
Location of march tech day needs updating before this can be merged

2018-03-15 19:27 UTC, Adimote requested changes
One quick fix needed for the link

2018-03-15 19:27 UTC, Adimote commented on data/locations.yml
> +  link: http://data.southampton.ac.uk/building/25.html
the link should be http://data.southampton.ac.uk/building/59.html not 25.

2018-03-15 19:30 UTC, Adimote approved these changes

2018-03-15 19:31 UTC, merged